apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
  namespace: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: spring-site
        image: m145/devops-auto:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: spring-entrypoint
  namespace: spring
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
